version: '3.8'

services:
  app:
    image: phonebook-fe-prod
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: phonebook-fe-prod # This will name the container phonebook-frontend-prod

  server:
    image: phonebook-be-prod
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
    container_name: phonebook-be-prod # This will name the container phonebook-be-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    container_name: reverse-proxy-phonebook
    depends_on:
      - app # wait for the frontend container to be started